baseURL: 'http://example.org/'
languageCode: 'en-us'
title: 'Каперсы'
paginate: 6
disqusShortname: yourdiscussshortname
taxonomies:
  category: categories
  embedder: embedders
  tag: tags
params:
  count: ["1","2","3","4","5","6"]
  ssss: "ssss"

mainSections: ["it","embedder"]
