languageCode: 'en-us'
title: 'Каперсы'
description: "Кароч я тут поднакатал ты там глянь)) It Embedder @izy_di"
paginate: 6
disqusShortname: http-capers-fun
url: 'capers.fun'
menu:
  main:
  - identifier: IT
    name: IT
    title: IT
    url: /it/
  - identifier: Embedder
    name: Embedder
    title: Embedder
    url: /embedder/

taxonomies:
  category: categories
  embedder: embedders
  tag: tags
params:
  mainSections: ["embedder", "it"]
